# https://github.com/soywod/himalaya
# https://pimalaya.org/himalaya/

# Represents the full display name of the user. It is used for building the
# sender address From when composing emails.
display-name = "Bryan Hoang"
# Represents the signature to add at the bottom of all emails. It can be a
# string or a path to a signature file. The signature supports TOML multiline.
signature = """
Bryan Hoang
Software Developer
bryan@bryanhoang.dev
"""
# Represents the directory to download attachments in.
downloads-dir = "~/Downloads"

[personal]
default = true
email = "bryan@bryanhoang.dev"

backend = "imap"
imap-host = "127.0.0.1"
imap-auth = "passwd"
imap-login = "bryan@bryanhoang.dev"
imap-passwd-cmd = "pass show email/protonmail"
imap-port = 1143
imap-starttls = true

sender = "smtp"
smtp-host = "127.0.0.1"
smtp-auth = "passwd"
smtp-login = "bryan@bryanhoang.dev"
smtp-passwd-cmd = "pass show email/protonmail"
smtp-port = 1025
smtp-starttls = true

[personal.folder-aliases]
