[flags]
# Whether to group processes with the same name together by default.
group_processes = true
# Show the battery widgets
battery = true
# Shows an indicator in table widgets tracking where in the list you are.
show_table_scroll_position = true
# Show processes as their commands by default in the process widget.
process_command = true
# Shows GPU(s) memory
enable_gpu_memory = true

# Catppuccin Mocha
[styles.tables]
headers = { color = "#f5e0dc" }
[styles.cpu]
all_entry_color = "#f5e0dc"
avg_entry_color = "#eba0ac"
cpu_core_colors = [
	"#f38ba8",
	"#fab387",
	"#f9e2af",
	"#a6e3a1",
	"#74c7ec",
	"#cba6f7",
]
[styles.memory]
arc_color = "#89dceb"
gpu_colors = ["#74c7ec", "#cba6f7", "#f38ba8", "#fab387", "#f9e2af", "#a6e3a1"]
ram_color = "#a6e3a1"
swap_color = "#fab387"
[styles.network]
rx_color = "#a6e3a1"
tx_color = "#f38ba8"
[styles.widgets]
border_color = "#585b70"
selected_border_color = "#f5c2e7"
selected_text = { color = "#11111b", bg_color = "#cba6f7" }
text = { color = "#cdd6f4" }
widget_title = { color = "#f2cdcd" }
[styles.graphs]
graph_color = "#a6adc8"
[styles.battery]
high_battery_color = "#a6e3a1"
low_battery_color = "#f38ba8"
medium_battery_color = "#f9e2af"
