tap "homebrew/bundle"
tap "oven-sh/bun"
brew "bun"
brew "hadolint"
brew "lua-language-server"
brew "marksman"
brew "pnpm"
brew "vale"
brew "clipboard"
# GIT utilities -- repo summary, repl, changelog population, author commit
# percentages and more (tj/git-extras).
brew "git-extras"
