[tool_alias]
aube = "github:jdx/aube"
dab = "dotnet:microsoft.dataapibuilder"
fff-mcp = "github:dmtrKovalenko/fff"
hunkdiff = "npm:hunkdiff"
monaco = "github:dynatrace/dynatrace-configuration-as-code"
op = "http:op"
pac = "dotnet:Microsoft.PowerApps.CLI.Tool"
rage = "github:str4d/rage"
sonarqube-cli = "http:sonarqube-cli"
vscode-langservers-extracted = "npm:vscode-langservers-extracted"

[tools]
atuin = "latest"
aube = { version = "latest", minimum_release_age = "0d" }
betterleaks = "latest"
bun = "latest"
cargo-binstall = "latest"
"cargo:cargo-cache" = "latest"
"cargo:git-absorb" = "latest"
"cargo:git-grab" = "latest"
cocogitto = "latest"
delta = "latest"
editorconfig-checker = "latest"
gh = "latest"
git-filter-repo = "latest"
"github:rtk-ai/rtk" = "latest"
"github:vslavik/diff-pdf" = "latest"
go = "latest"
"go:github.com/sigstore/gitsign" = "latest"
harper-cli = "latest"
harper-ls = "latest"
hk = { version = "latest", minimum_release_age = "1d" }
jaq = "latest"
lychee = "latest"
node = "latest"
"npm:sfw" = "latest"
"npm:skills" = "latest"
opencode = { version = "latest", minimum_release_age = "0d" }
oxfmt = "latest"
oxlint = "latest"
pkl = "latest"
pnpm = { version = "latest", minimum_release_age = "0d" }
rmz = "latest"
rumdl = "latest"
rust = "nightly"
sccache = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
taplo = "latest"
television = "latest"
topgrade = "latest"
tree-sitter = "latest"
typos = "latest"
usage = { version = "latest", minimum_release_age = "0d" }
uv = "latest"
zoxide = "latest"

[tools.vscode-langservers-extracted]
aube_args = "--allow-build=core-js"
version = "latest"

[tools.fff-mcp]
minimum_release_age = "1d"
version = "latest"

[tools.fff-mcp.platforms]
windows-x64 = { asset_pattern = 'fff-mcp-{{arch(x64="x86_64")}}-pc-{{os()}}-msvc.exe', bin = "fff-mcp.exe" }

[tools.hunkdiff]
aube_args = "--allow-build=bun"
version = "latest"
