[tools]
"aqua:sigstore/gitsign" = "latest"
"aqua:str4d/rage" = "latest"
atuin = "latest"
aube = { version = "latest", minimum_release_age = "1d" }
betterleaks = "latest"
bitwarden = "latest"
bun = "latest"
cargo-binstall = "latest"
"cargo:cargo-cache" = "latest"
"cargo:git-absorb" = "latest"
"cargo:git-grab" = "latest"
"cargo:tailspin" = "latest"
"cargo:tealdeer" = "latest"
cocogitto = "latest"
delta = "latest"
editorconfig-checker = "latest"
gh = "latest"
git-filter-repo = "latest"
go = "latest"
"go:github.com/dnnrly/abbreviate" = "latest"
harper-cli = "latest"
harper-ls = "latest"
hk = { version = "latest", minimum_release_age = "1d" }
jaq = "latest"
jq = "latest"
lychee = "latest"
node = "latest"
"npm:sfw" = "latest"
"npm:skills" = "latest"
opencode = { version = "latest", minimum_release_age = "1d" }
oxfmt = "latest"
oxlint = "latest"
pkl = "latest"
pnpm = { version = "latest", minimum_release_age = "1d" }
rmz = "latest"
rumdl = "latest"
rust = "nightly"
sccache = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
taplo = "latest"
television = "latest"
topgrade = "latest"
tree-sitter = "latest"
typos = "latest"
usage = "latest"
uv = "latest"
zizmor = "latest"
zoxide = "latest"
