# https://mise.jdx.dev/configuration/settings.html

[settings]
color_theme = "catppuccin"
env_cache = true
experimental = true
minimum_release_age = "1d"
paranoid = true

[settings.cargo]
binstall_native = true
binstall_only = true
binstall_quickinstall = true

[settings.python]
uv_venv_auto = true
