[tools]
"aqua:betterleaks/betterleaks" = "latest"
"aqua:sigstore/gitsign" = "latest"
cocogitto = "latest"
editorconfig-checker = "latest"
go = "latest"
harper-cli = "latest"
jq = "latest"
lychee = "latest"
node = "latest"
pkl = "latest"
rumdl = "latest"
shellcheck = "latest"
shfmt = "latest"
taplo = "latest"
usage = "latest"
uv = "latest"

[tools.aube]
minimum_release_age = "1d"
version = "latest"

[tools."github:anomalyco/opencode"]
minimum_release_age = "0d"
version = "latest"

[tools.hk]
minimum_release_age = "1d"
version = "latest"
