[tools]
"aqua:betterleaks/betterleaks" = "latest"
aube = "latest"
editorconfig-checker = "latest"
"github:anomalyco/opencode" = "latest"
go = "latest"
harper-cli = "latest"
hk = "latest"
jq = "latest"
node = "latest"
pkl = "latest"
shellcheck = "latest"
shfmt = "latest"
taplo = "latest"
uv = "latest"
