#!/usr/bin/env sh
# -*- coding: utf-8 -*-

# Searched last
export PATH="${TEXDIR}"/bin/x86_64-linux:"${PATH}"
export PATH=/var/lib/flatpak/exports/bin:"${PATH}"
[ -s /home/linuxbrew/.linuxbrew/bin/brew ] \
	&& eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
[ -s "${HOME}"/.linuxbrew/bin/brew ] \
	&& eval "$("${HOME}"/.linuxbrew/bin/brew shellenv)"
export PATH="${XDG_CONFIG_HOME}"/rofi/scripts:"${PATH}"
export PATH="${XDG_DATA_HOME}"/umake/bin:"${PATH}"
export PATH="${PNPM_HOME}:${PATH}"
export PATH="${DENO_INSTALL}"/bin:"${PATH}"
export PATH="${BUN_INSTALL}"/bin:"${PATH}"
# shellcheck disable=SC1091
[ -f "${CARGO_HOME}"/env ] && . "${CARGO_HOME}"/env
export PATH="${HOME}"/.spicetify:"${PATH}"
export PATH="${ASDF_DIR}"/bin:"${PATH}"
export PATH="${ASDF_DIR}"/shims:"${PATH}"
export PATH="${XDG_BIN_HOME}":"${PATH}"
# Searched first
