AllCops:
  NewCops: enable
Layout/LineLength:
  Max: 80
Layout/FirstMethodArgumentLineBreak:
  Enabled: true

# https://github.com/rubocop/rubocop/issues/9373#issuecomment-760300711
Layout/IndentationWidth:
  Width: 1
Layout/IndentationStyle:
  EnforcedStyle: tabs

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/MethodCallWithArgsParentheses:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
