AllCops:
  NewCops: enable
Layout/LineLength:
  Max: 80
Layout/FirstMethodArgumentLineBreak:
  Enabled: true

# https://github.com/rubocop/rubocop/issues/9373#issuecomment-760300711
Layout/IndentationWidth:
  Width: 1
Layout/IndentationStyle:
  EnforcedStyle: tabs
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect
Layout/MultilineMethodCallIndentation:
  # `rubyfmt`
  EnforcedStyle: indented

# https://docs.rubocop.org/rubocop/cops_style.html
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: false
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInChaining: true
  AllowParenthesesInCamelCaseMethod: true
  AllowParenthesesInStringInterpolation: true
Style/MethodCallWithoutArgsParentheses:
  AllowedPatterns: ['.*']
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
