#!/usr/bin/env sh
#
# shellcheck disable=SC2154

# https://gist.github.com/abairo/5e2ed2faeadcc7abf43cda37826b2fbc#if-you-get-an-incosistent-theme-on-some-parts-of-the-system-or-windows-try-this
xsetroot -cursor_name left_ptr &

xrdb -merge "$XDG_CONFIG_HOME"/X11/xresources

setxkbmap -option ctrl:swapcaps
setxkbmap -option compose:rctrl

session=${1:-${WM:-i3}}
exec dbus-launch "$session"
