# https://github.com/rust-motd/rust-motd/blob/main/example_config.toml

[banner]
color = "blue"
command = """
echo \"MOTD: Welcome, $(whoami)@$(hostname)\" | figlet -f slant\
"""

[service_status]
docker = 'docker'

[user_service_status]
ssh-agent = 'ssh-agent'
gpg-agent = "gpg-agent"
tmux = 'tmux'
spotifyd = 'spotifyd'

[filesystems]
root = "/"
home = '/home'

[memory]
swap_pos = "beside" # or "below" or "none"

[last_login]
bryan = 2

[uptime]
prefix = "Uptime:"

[last_run]
