# [global]
# progress_full_character = "="
# progress_empty_character = "="
# progress_prefix = "["
# progress_suffix = "]"
# time_format = "%Y-%m-%d %H:%M:%S"

[banner]
color = "blue"
command = """
echo \"MOTD: Welcome, $(whoami)@$(hostname)\" | figlet -f slant\
"""

[weather]
# url = "https://wttr.in/"
loc = 'Kingston Ontario'

[service_status]
docker = 'docker'
# Accounts = "accounts-daemon"
# Cron = "cron"

# [docker_status]
# Local containers MUST start with a slash
# https://github.com/moby/moby/issues/6705
# "/nextcloud-nextcloud-1" = "Nextcloud"
# "/nextcloud-nextcloud-mariadb-1" = "Nextcloud Database"

[user_service_status]
ssh-agent = 'ssh-agent'
gpg-agent = "gpg-agent"
tmux = 'tmux'
spotifyd = 'spotifyd'

# [ssl_certificates]
# sort_method = "manual"
#
#    [ssl_certificates.certs]
#    CertName1 = "/path/to/cert1.pem"
#    CertName2 = "/path/to/cert2.pem"

[filesystems]
root = "/"
home = '/home'

[memory]
swap_pos = "beside" # or "below" or "none"

# [fail2_ban]
# jails = ["sshd"]

[last_login]
bryan = 2

[uptime]
prefix = "Uptime:"

[last_run]
