# https://github.com/rust-motd/rust-motd/blob/main/example_config.toml

[banner]
color = 'blue'
command = """
cfonts "MOTD: Welcome,|$(whoami)@$(hostname)" --font tiny
"""

[service_status]
dbus-broker = 'dbus-broker'
docker = 'docker'
nginx = 'nginx'
systemd-timesyncd = 'systemd-timesyncd'

[user_service_status]
docuum = 'docuum'
dunst = 'dunst'
emacs = 'emacs'
gpg-agent = 'gpg-agent'
lemonade = 'lemonade'
spotifyd = 'spotifyd'
ssh-agent = 'ssh-agent'
tmux = 'tmux'

[filesystems]
root = '/'

[memory]
swap_pos = 'beside'

[last_login]
bryan = 2

[uptime]
prefix = 'Uptime:'

[last_run]
