
[theme]
theme = "nord-dark"

[theme.overrides]
separator = "<span font='16'> </span>"

[icons]
icons = "awesome6"

[[block]]
block = "focused_window"
format = "$title.rot-str(16)|"

[[block]]
block = "music"
format = "$combo.rot-str(16) $play|"

[[block]]
block = "docker"
format = "$running/$total"
interval = 2

[[block]]
block = "external_ip"

[[block]]
alert_unit = "GB"
block = "disk_space"
format = "$available.eng(2) available"
[[block.click]]
button = "right"
update = true

[[block]]
block = "memory"

[[block]]
block = "load"
format = "$1m.eng(4) $5m.eng(4) $15m.eng(4)"

[[block]]
block = "bluetooth"
hide_disconnected = true
mac = "88:C9:E8:00:D0:F9"

[[block]]
block = "sound"

[[block]]
block = "time"
format = "%a %Y-%m-%d %R"
interval = 5

[[block]]
block = "battery"
hide_missing = true

[[block]]
block = "github"
hide_if_total_is_zero = true
info = ["total"]
warning = ["mention", "review_requested"]
