[theme]
theme = "ctp-mocha"

[theme.overrides]
idle_bg = "#1E1E2E"
idle_fg = "#CDD6F4"
# Remove powerline separators.
separator = "<span></span>"

[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
format = " $title.str(max_w:16,rot_interval:0.5) |"

[[block]]
block = "docker"
format = " $icon $running.eng(w:1)/$total.eng(w:1) "
[block.theme_overrides]
idle_bg = "#89B4FA"
idle_fg = "#1E1E2E"

[[block]]
block = "disk_space"
format = " $icon $available.eng(w:1)/$total "
[[block.click]]
button = "right"
update = true

[[block]]
block = "memory"
format = " $icon $mem_avail.eng(w:1,u:B,p:M)/$mem_total.eng(w:1,u:B,p:M) "
[block.theme_overrides]
idle_bg = "#FF79C6"
idle_fg = "#282A36"

[[block]]
block = "cpu"
format = " $icon $utilization "
format_alt = " $icon $barchart $utilization "

[[block]]
block = "load"
format = " $icon $1m.eng(w:3) $5m.eng(w:3) $15m.eng(w:3) "
[block.theme_overrides]
idle_bg = "#A6E3A1"
idle_fg = "#1E1E2E"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:16,rot_interval:0.5) $play |}"

[[block]]
block = "bluetooth"
# WH-1000XM5
mac = "88:C9:E8:00:D0:F9"
[block.theme_overrides]
idle_bg = "#74C7EC"
idle_fg = "#1E1E2E"

[[block]]
block = "sound"
show_volume_when_muted = true
step_width = 10
[block.theme_overrides]
idle_bg = "#FFB86C"
idle_fg = "#282A36"

[[block]]
block = "battery"
# Hide missing battery.
missing_format = ""

[[block]]
block = "uptime"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%F %R') "
[block.theme_overrides]
idle_bg = "#BD93F9"
idle_fg = "#21222C"

# Fails to get property on some machines.
# [[block]]
# block = "notify"
