[theme]
theme = "dracula"

[theme.overrides]
# Make powerline separators match height of blocks.
idle_bg = "#44475A"
idle_fg = "#F8F8F2"
separator = "<span></span>"

[icons]
icons = "awesome6"

[[block]]
block = "focused_window"

[[block]]
block = "docker"
format = " $icon $running.eng(w:1)/$total.eng(w:1) "
[block.theme_overrides]
idle_bg = "#8BE9FD"
idle_fg = "#282A36"

[[block]]
alert_unit = "GB"
block = "disk_space"
format = " $icon $available.eng(w:1)/$total "
[[block.click]]
button = "right"
update = true

[[block]]
block = "memory"
format = " $icon $mem_avail.eng(w:1,u:B,p:M)/$mem_total.eng(w:1,u:B,p:M) "
[block.theme_overrides]
idle_bg = "#FF79C6"
idle_fg = "#282A36"

[[block]]
block = "load"
format = " $icon $1m.eng(w:3) $5m.eng(w:3) $15m.eng(w:3) "
[block.theme_overrides]
idle_bg = "#50FA7B"
idle_fg = "#282A36"

[[block]]
block = "cpu"
format = " $icon $barchart $utilization "

[[block]]
block = "music"

[[block]]
block = "bluetooth"
# WH-1000XM5
mac = "88:C9:E8:00:D0:F9"
[block.theme_overrides]
idle_bg = "#8BE9FD"
idle_fg = "#21222C"

[[block]]
block = "sound"
show_volume_when_muted = true
step_width = 10
[block.theme_overrides]
idle_bg = "#FFB86C"
idle_fg = "#282A36"

[[block]]
block = "battery"
# Hide missing battery.
missing_format = ""

[[block]]
block = "uptime"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %F %R') "
[block.theme_overrides]
idle_bg = "#BD93F9"
idle_fg = "#21222C"

[[block]]
block = "apt"

[[block]]
block = "notify"
