# https://docs.atuin.sh/configuration/config/

history_filter = ["Password"]
keymap_mode = "auto"
search_mode = "daemon-fuzzy"
store_failed = false
style = "auto"

[daemon]
autostart = true
enabled = true

[logs]
dir = "~/.local/share/atuin/logs"

[theme]
name = "catppuccin-mocha-blue"

[sync]
records = true
