# https://docs.atuin.sh/latest/configuration/config/

history_filter = ["BW_SESSION="]
search_mode = "daemon-fuzzy"
store_failed = false
style = "auto"

[daemon]
autostart = true
enabled = true

[logs]
dir = "~/.local/share/atuin/logs"

[theme]
name = "catppuccin-mocha-blue"
