globalBinDir = ["~/.local/bin"]
jailBuildExclusions = [
	"@opencode-ai/cli",
	"bun",
	"core-js",
	"@nubjs/nub",
	"@azure-devops/mcp",
]
minimumReleaseAgeExclude = ["@opencode-ai/*"]
paranoid = true
trustPolicyExclude = []
