# ~/.config/starship.toml

format = "$all"

# Add a blank line at the start of the prompt
add_newline = true

# The character module shows a character (usually an arrow) beside where the
# text is entered in your terminal.
[character]
error_symbol = "[\\$](bold red)"
success_symbol = "[\\$](bold green)"

[env_var]
default = "unknown shell"
variable = "SHELL"

[hostname]
ssh_only = false

# The python module shows the currently installed version of Python and the
# current Python virtual environment if one is activated.
[python]
# Use pyenv to get Python version
pyenv_version_name = true
# Configures the python binaries that Starship should executes when getting the
# version.
python_binary = ["python3", "python", "python2"]

[shell]
# Disables the shell module.
disabled = true

[status]
disabled = true
# Enable symbols mapping from exit code
map_symbol = true

[time]
disabled = true

[username]
disabled = false
show_always = true
