# ~/.config/starship.toml

format = "$all"

# Add a blank line at the start of the prompt
add_newline = true

# The character module shows a character (usually an arrow) beside where the
# text is entered in your terminal.
[character]
error_symbol = "[\\$](bold red)"
success_symbol = "[\\$](bold green)"

[cmd_duration]
disabled = false

[env_var]
default = "unknown shell"
disabled = true
style = "black bold"
variable = "SHELL"

[hostname]
ssh_only = false

[memory_usage]
disabled = false
threshold = -1

[package]
disabled = true

# The python module shows the currently installed version of Python and the
# current Python virtual environment if one is activated.
[python]
# Use pyenv to get Python version
pyenv_version_name = true
# Configures the python binaries that Starship should executes when getting the
# version.
format = 'via [${symbol}${pyenv_prefix}(${version} )($virtualenv )]($style)'
python_binary = ["python3", "python", "python2"]

[shell]
# Disables the shell module.
disabled = true
unknown_indicator = "mystery shell"

[status]
disabled = true
# Enable symbols mapping from exit code
map_symbol = true

[time]
disabled = true

[username]
format = "[$user]($style) at "
show_always = true

[custom.shell]
# The command whose output should be printed. The command will be passed on
# stdin to the shell.
command = "echo $0"
format = "with [$output]($style) "
style = "black bold"
# A shell command used as a condition to show the module. The module will be
# shown if the command returns a 0 status code.
when = "true"
