# https://doc.rust-lang.org/cargo/reference/config.html

# https://doc.rust-lang.org/nightly/cargo/reference/unstable.html
[unstable]
gc = true
# https://github.com/rust-lang/cargo/issues/11813
# [unstable.gitoxide]
# checkout = true
# fetch = true
# internal_use_git2 = false
