#!/usr/bin/env sh
#
# shellcheck disable=SC1091

if command -v ripsecrets >/dev/null 2>&1; then
	set +e
	ripsecrets --strict-ignore \
		"$(git diff --cached --name-only --diff-filter=ACM)" 2>/dev/null
	status=$?
	set -e

	# Don't exit if amending w/ empty diff leads to exit code of 2.
	if [ "$status" -ne 0 ] && [ "$status" -ne 2 ]; then
		exit "$status"
	fi
fi

pnpm lint-staged
