import = ['C:\Users\bryan\src\github.com\dracula\alacritty\dracula.yml']
live_config_reload = true

[env]
SHLVL = "0"

[font.normal]
family = "BerkeleyMono Nerd Font Mono"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 0.75
resize_increments = true
startup_mode = "Maximized"

[window.dimensions]
columns = 120
lines = 32

[window.padding]
x = 8
y = 0
