#!/usr/bin/env sh
#
# shellcheck disable=SC2034

remote="$1"
url="$2"

# Avoid accidentally pushing an invalid CI config file.
if [ -s .gitlab-ci.yml ] && command -v glab >/dev/null; then
	glab ci lint
fi
