[ui]
use_nerd_font_icons = true
show_help_bar = false
input_bar_position = "bottom"
theme = "catppuccin"

[keybindings.Channel]
# Quit the application
quit = ["esc", "ctrl-c", "ctrl-g"]
# Toggle the help bar
toggle_help = "ctrl-h"
