[ui]
input_bar_position = "bottom"
show_help_bar = false
theme = "catppuccin"
use_nerd_font_icons = true

[keybindings]
# Application control
# ------------------
ctrl-c = "quit"
ctrl-g = "quit"
esc = "quit"

[shell_integration.channel_triggers]
"git-branch-local" = ["git switch"]
