[ui]
use_nerd_font_icons = true
show_help_bar = false
input_bar_position = "bottom"
theme = "catppuccin"

[keybindings]
# Application control
# ------------------
esc = "quit"
ctrl-c = "quit"
ctrl-g = "quit"
