format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
${custom.git_url}\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
${custom.git_email}\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$bun\
${custom.pnpm}\
${custom.yarn}\
${custom.npm}\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$line_break\
$character
"""

add_newline = true
command_timeout = 1000
continuation_prompt = '[>](bright-black) '
scan_timeout = 30

[bun]
format = '[$symbol($version )]($style)'

[c]
format = "[$symbol($version(-$name) )]($style)"

[character]
error_symbol = '[\$](bold red)'
success_symbol = '[\$](bold green)'

[cobol]
format = "[$symbol($version )]($style)"

[cmake]
format = "[$symbol($version )]($style)"
version_format = "v${major}.${minor}"

[cmd_duration]
format = '[$duration]($style) '
min_time = 2_000
show_notifications = true

[conda]
format = "[$symbol$environment]($style) "
ignore_base = false

[container]
format = '[$symbol ]($style)'

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "

[deno]
format = '[$symbol($version )]($style)'
version_format = 'v${major}.${minor}'

[docker_context]
disabled = true
format = "[$symbol$context]($style) "

[gcloud]
# The module isn't very useful :(
disabled = true

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_metrics]
disabled = false

[hostname]
format = "[$ssh_symbol$hostname]($style):"
ssh_symbol = ""
trim_at = ""

[lua]
format = '[$symbol($version )]($style)'

[memory_usage]
disabled = true
format = '$symbol[${ram}( | ${swap})]($style) '

[nodejs]
format = '[$symbol($version )]($style)'
version_format = "v${major}"

[os]
disabled = true

[package]
format = '[$symbol$version]($style) '

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
python_binary = ["python3", "python", "python2"]
version_format = "v${major}.${minor}"

[ruby]
format = "[$symbol($version )]($style)"

[rust]
format = '[$symbol($version )]($style)'
version_format = 'v${major}.${minor}'

[shell]
disabled = false

[shlvl]
disabled = false

[status]
disabled = false
map_symbol = true
pipestatus = true
pipestatus_format = '\[$pipestatus\] => [$symbol$common_meaning$signal_name$maybe_int ]($style)'
pipestatus_segment_format = '[$symbol$status]($style)'

[sudo]
disabled = false
format = "[$symbol]($style)"

[time]
disabled = true

[username]
format = "[$user]($style)@"

[custom.pnpm]
command = "pnpm --version | awk -F '.' '{print \"v\"$1}'"
description = "The currently installed version of pnpm"
detect_files = ['pnpm-lock.yaml']
disabled = true
format = '[$symbol($output )]($style)'
style = "bold yellow"
symbol = 'p '

# To help switch between npm versions when it matters -_-
[custom.yarn]
command = "yarn --version | awk -F '.' '{print \"v\"$1}'"
description = "The currently installed version of yarn"
detect_files = ['yarn.lock']
disabled = true
format = '[$symbol($output )]($style)'
style = "bold blue"
symbol = ' '

# To help switch between npm versions when it matters -_-
[custom.npm]
command = "npm --version | awk -F '.' '{print $1}'"
description = "The currently installed version of npm"
detect_files = ['package-lock.json']
disabled = true
format = '[$symbol(v$output )]($style)'
style = "bold red"
symbol = ' '

[custom.git_url]
command = "check-git-remote"
description = "Display symbol for remote Git server"
format = "[$output]($style) "
require_repo = true
style = "white"
when = "true"

[custom.git_email]
command = 'print-git-email-symbol'
description = 'The currently configured Git user.email'
format = '[<$output> ]($style)'
require_repo = true
style = 'blue'
when = 'true'

[custom.direnv]
command = "echo 'direnv'"
description = "The fact that direnv is being used"
disabled = true
format = "using [$output]($style) "
style = "purple"
when = "[[ -n \"${DIRENV_DIR}\" ]]"
