# https://docs.helix-editor.com/configuration.html
theme = "gruvbox_dark_hard_transparent"

[editor]
line-number = "relative"
rulers = [80, 100, 120]
bufferline = "multiple"
color-modes = true
cursorline = true

[editor.statusline]
left = [
	"mode",
	"file-name",
]
center = [
	"spinner",
]
right = [
	"diagnostics",
	"workspace-diagnostics",
	"position",
	"total-line-numbers",
	"position-percentage",
	"file-line-ending",
	"file-encoding",
]

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"

[editor.indent-guides]
render = true
